apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-flask-config
  namespace: namespace-workflow-1790192756992
  labels:
    app.kubernetes.io/name: demo-flask
    kubernetes.azure.com/generator: devhub
data: